#!/bin/bash
# This script helps you set up the project

echo "=== Quality Products Blog - Setup Instructions ==="
echo ""
echo "STEP 1: Create a GitHub account if you don't have one"
echo "        Go to: https://github.com/signup"
echo ""
echo "STEP 2: Create a new repository"
echo "        - Go to: https://github.com/new"
echo "        - Name it: quality-products-blog"
echo "        - Keep it PUBLIC (for free Vercel deployment)"
echo "        - DO NOT initialize with README"
echo "        - Click 'Create repository'"
echo ""
echo "STEP 3: On your Windows computer, open PowerShell or CMD"
echo "        and run these commands one by one:"
echo ""
echo "        # Install Git if not already installed"
echo "        # Download from: https://git-scm.com/download/win"
echo ""
echo "        # Install Node.js if not already installed"  
echo "        # Download from: https://nodejs.org/"
echo ""
echo "        # Clone the repository"
echo "        git clone https://github.com/YOUR_USERNAME/quality-products-blog.git"
echo "        cd quality-products-blog"
echo ""
echo "STEP 4: Deploy to Vercel (Easiest)"
echo "        - Go to: https://vercel.com/signup"
echo "        - Sign up with your GitHub account"
echo "        - Click 'Import Project'"
echo "        - Select your 'quality-products-blog' repository"
echo "        - Click 'Deploy'"
echo ""
echo "That's it! Vercel will automatically build and deploy your site."
